- python
  - python is a programing paradism  means  it supports functional programming language
- procedure oriented language  
   - procedure oriented means write our programing language iusing functions,object and calsses
- object oriented language
   - object::real world entity or it is a physical entity representing the
   - class::logical entity contains logic of the application

In [ ]:
class class_name:
    variables   

In [1]:
print("hi hello")

hi hello


In [2]:
8+9

17

In [3]:
class Hi:
    a=30
    b=20
    name="apssdc"
    def show():
        print("i am from show() function")
Hi.show()        
        
        
        

i am from show() function


In [4]:
print(Hi.a,Hi.b)

30 20


In [5]:
class Hi:
    name="apssdc"
    program_name="python"
    def display():
        print("i am from display function()")
    def show():  
         print("i am from show function()")
print(Hi.name,Hi.program_name)
print(Hi.display())
            

apssdc python
i am from display function()
None


In [6]:
print(Hi.display())

i am from display function()
None


In [9]:
class Hello():
    def display():
        print("i am from display function()")
        return("i am from return statement")
def show():
         print("i am from show function()")
print(Hello.display())
print(Hello.show())
        

i am from display function()
i am from return statement


AttributeError: type object 'Hello' has no attribute 'show'

In [ ]:
# in java object declaration


In [12]:
class Hi:
    name="apssdc"
    program_name="python"
    def display(self):
        print("i am from display function()")
    def show():  
         print("i am from show function()")
obj=Hi()            
print(obj.name,obj.program_name)
print(obj.display())
            

apssdc python
i am from display function()
None


### Constructor
- constructor:without using object we will call methods
-  in java::class name should be show as method name
- in python::we will use one special method to define constructor
-  __int(self)__

In [21]:
class Hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("hi",self.name)
    def display(self):
        print("your roll_no",self.roll_no)
obj=Hai('divya','21850520')
obj.display()
    

hi divya
your roll_no 21850520


### Inheritance
- inherit something from parent class to child class

In [ ]:
class A:
    #a,b=10,20
class B(A):
    #c,d=40,50

In [22]:
class A:
    a,b=10,20
    def msg():
        print("i am from class A")
class B(A):
    c,d=40,50
    def msg1():
        print("i am from class B")
obj=0
print(obj.c,obj.a)
obj.msg()
obj.msg1()

AttributeError: 'int' object has no attribute 'c'

### Python libraries for data science
- organizing,processing,analysing
- apply the data visualization
- extracting data from the source
- nearly 20 python libraries
### top
- numpy
- pandas
- matplotlib 

### numpy
- (num+py) means numerical data+python
- it is a fundamental package for scientific computing
- numpy is python library
- it is used to create multidimensional array for fast operations
  - its dealing with mathematical scientific statical data
- numpy contains a powerful n dimensional arrays objects which in the form of 
- we can intilize numpy array from nested python lists

In [ ]:
# how to install numpy
- pip install numpy

In [3]:
# how to import and use many 
import numpy as np

In [4]:
# how to find the numpy version
np.__version__

'1.20.3'

In [17]:
# how to create numpy arrays
import numpy as np
a=np.array([1,2,3,4])# single dimensional number
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [16]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)
print(type(a2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [18]:
#  to know about the shape of the array 
a2.shape

(2, 3)

In [22]:
li=[2,3,4,'h','i']
print(type(li))
a2=np.array(li)
print(a2)
print(type(a2))

<class 'list'>
['2' '3' '4' 'h' 'i']
<class 'numpy.ndarray'>


In [26]:
b=np.array([[1,2,3],[4,5,6]])
print(a1)

[[1 2 3]
 [4 5 6]]


In [27]:
print(b.shape)

(2, 3)


In [31]:
b.itemsize

4

In [33]:
b.ndim

1

In [32]:
#range
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [34]:
a=np.array(range(1,10,2))
a

array([1, 3, 5, 7, 9])

In [37]:
# arrange():third party of many libraries
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [39]:
x=np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [43]:
# reshape of array
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("before reshape",a1)
print(a2.ndim)
a2=a2.reshape(4,7)
print("after reshape",a2)
print(a2.reshape)
print(a2.ndim)

(8,)
before reshape [1 2 3 4 5 6 7 8]
1


ValueError: cannot reshape array of size 5 into shape (4,7)

In [51]:
# resize of array(it modifies
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3)
print(a1)
print(a1.shape)
a2.resize(3,3)
print(a1)
print(a1.shape)



[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[1 2 3]
(3,)


In [46]:
import numpy as np

In [52]:
# zero array
import numpy as np
a1=np.zero(3)
a2=np.zero(2,4),dtype="int64"
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)


SyntaxError: cannot assign to function call (Temp/ipykernel_3612/2523176640.py, line 4)

In [49]:
a2=np.ones(3,dtype=int64)
print(a2)
np.ones(6,5),dtype="int64"

SyntaxError: cannot assign to function call (Temp/ipykernel_3612/1655958438.py, line 3)

In [56]:
# full array full(dimensions,specified numbers)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [57]:
np.diag(a)

array([7, 7, 7])

In [58]:
np.full(3,100)

array([100, 100, 100])

In [59]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [60]:
# eye array
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [ ]:
f=np.random.randint(1,30)

In [64]:
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [65]:
a.max()

7

In [66]:
a.min()

7

In [ ]:
a=np.arange(9.reshape(3,3))
a

In [ ]:
b=np.arrange()

In [ ]:
print(a+b)
print("************")
print(a-b)
print("_________")
print(a*b)
print("$$$$$$$$$$$$")
print(a%d)
print(np.max(a))
print(np.min(b))


In [78]:
a+3

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [79]:
a+10

array([[17, 17, 17],
       [17, 17, 17],
       [17, 17, 17]])

In [80]:
np.log2(2)

1.0

In [75]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [77]:
np.tan(30)

-6.405331196646276

In [81]:
np.exp(1)

2.718281828459045

In [82]:
np.sin(30)

-0.9880316240928618

In [83]:
np.cos(30)

0.15425144988758405

In [84]:
np.cos(0)

1.0

 ### Pandas
 - pandas is the datascience packages
 - it is used for
   - data manupulation(modification and updations)
   - data analysis
   - data cleaning to remove unnecessary data from data sciences
 - contains mainly two data structures in pandas
   - series-sequence of a data
   - dataframes-data with rows and columns

   